/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbcgui;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author wissam
 */
public class LoginForm extends javax.swing.JFrame {

    myDBCon dbCon;
    boolean validLogin = false;
    ResultSet rs;

    /**
     * Creates new form LoginForm
     */
    
    public String passEncryption(String password)
    {   
        char[] pass = password.toCharArray();
        char[] encrypt = new char[pass.length];
        
        String skey = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        char[] key = skey.toCharArray();
        
        for (int i = 0; i < pass.length; i++)
        {
            int index = skey.indexOf(pass[i]);
            index = (index + 37) % key.length;
            encrypt[i] = key[index];
        }
        String encrypted = String.valueOf(encrypt);
        
        return encrypted;
    }
    
    public LoginForm() {
        initComponents();
        this.setLocationRelativeTo(null); // center the login form in the screen 
        dbCon = new myDBCon();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login to JDBC GUI");
        setBounds(new java.awt.Rectangle(600, 500, 0, 0));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 250, 110, 22);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 320, 100, 22);

        txtUsername.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername);
        txtUsername.setBounds(500, 250, 200, 28);

        txtPassword.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        getContentPane().add(txtPassword);
        txtPassword.setBounds(500, 310, 200, 28);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Login to Library System");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 80, 490, 44);

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(500, 390, 96, 36);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcgui/library.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-660, -50, 1770, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

        try {
            rs = dbCon.executeStatement("SELECT * FROM libraryusers WHERE username='"+txtUsername.getText().trim()+"'AND password='"+ passEncryption(txtPassword.getText().trim()) + "'");
            rs.beforeFirst();
            if (rs.next()) { // check current login user accounts searching for a match 
                // Valid Login User found
                validLogin = true;
                // create a new login user object and pass details to Menu form 
                (new Menu(new LoginUser(rs.getString("Username"), rs.getString("Name"), rs.getInt("Type")))).setVisible(true);
                this.dispose(); // remove this login from from memory 
            }

            if (!validLogin) { // this mean Invalid credentials 
                javax.swing.JLabel label = new javax.swing.JLabel("Wrong username/password.");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
                txtUsername.setText("");
                txtPassword.setText("");
            }

        } catch (SQLException e) { // this is an SQL error
            javax.swing.JLabel label = new javax.swing.JLabel("SQL Error - " + e.getMessage());
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
